added separate type files for every folder
JunDevHarsh/ReadmeEase pull request #32
Opened 2023-02-24 17:58 UTC by ehsaanchanga

@JunDevHarsh 
## Description

Fixes #

## Type of change

- [ ] Bug fix
- [ ] New feature
- [ ] Documentation update
- [ ] Other (please describe):

## Validation

- [ ] I have tested my changes locally and verified that they work as expected.
- [ ] I have updated the documentation (if applicable) to reflect the changes I've made.
- [ ] I have added unit tests (if applicable) to ensure my changes don't break existing functionality.

## Checklist

- [ ] I have read the [contributing guidelines](https://github.com/JunDevHarsh/ReadmeEase#contributing) and my pull request follows them.
- [ ] My code follows the code style of this project.
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added or updated tests to cover my changes.
- [ ] All new and existing tests passed.

## Related PRs

## Screenshots

## Labels

labels:

2023-02-25 04:30 UTC, JunDevHarsh commented
@ehsaanchanga, Thank you for making a PR. There is an error that needs to be fixed. Here is the screenshot of it.

![Screenshot 2023-02-24 172714](https://user-images.githubusercontent.com/94737463/221338184-c6883ae0-994f-4cb4-bf1e-3fd01ab3ef57.png)

2023-02-25 05:03 UTC, JunDevHarsh commented on src/components/Modal/types.ts
> +  id: string;
`id: string;` should be `id: string | string[]`

2023-02-25 05:05 UTC, JunDevHarsh requested changes
Need to make a little change in the file in `./src/components/Modal/Delete.tsx`

`id: string` should be `id: string | string[]`

2023-02-27 05:29 UTC, JunDevHarsh commented
> @JunDevHarsh fixed the types file

@ehsaanchanga, you have to update the `DeleteModalPropsType` block, not the `FileItemType` block. Here is the code you can look at:

```javascript
export type DeleteModalPropsType = {
  id: string; // change this line to 'id: string | string[]'
  toggleModal: React.Dispatch<React.SetStateAction<boolean>>;
};
```

2023-02-27 07:19 UTC, ehsaanchanga commented
@JunDevHarsh sorry for that . its done now

2023-02-27 07:49 UTC, JunDevHarsh approved these changes

2023-02-27 07:49 UTC, merged

2023-02-27 07:50 UTC, JunDevHarsh commented
Thank you @ehsaanchanga for your contribution,